version: "3.5"

services:
  nginx:
    ports:
      - "${NGINX_PORT_NO_SSL}:80"
      - "${NGINX_PORT}:443"
    volumes:
      - ./config/docker/nginx/dev.nginx.conf:/etc/nginx/nginx.conf
#      - ./config/docker/nginx/ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
#      - ./config/docker/nginx/ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
#      - ./config/docker/nginx/ssl/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
#      - ./config/docker/nginx/ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
#    networks:
#      micnetwork:
#        ipv4_address: 10.7.0.4

