version: "3.5"

services:
  nginx:
    ports:
      - "${NGINX_PORT_NO_SSL}:80"
      - "${NGINX_PORT}:443"
    volumes:
      - ./config/docker/nginx/prod.nginx.conf:/etc/nginx/nginx.conf
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "udp://${GRAYLOG_HOST}:${GRAYLOG_NGINX_PORT}"
#        tag: myitcareer_prod_nginx



